apiVersion: v2
name: Kit-Helmchart
type: application
description: My Helm cgart for K8s
version: 0.0.1 # This is the Helm Chart version
appVersion: "1.2.3" # This is the version of thw application being deployed